/* Autogenerated with kurento-module-creator */

#ifndef __PULSE_READER_OPENCV_IMPL_HPP__
#define __PULSE_READER_OPENCV_IMPL_HPP__

#include <OpenCVProcess.hpp>
#include "PulseReader.hpp"
#include <EventHandler.hpp>

namespace kurento
{
namespace module
{
namespace pulsereader
{

class PulseReaderOpenCVImpl : public virtual OpenCVProcess
{

public:

  PulseReaderOpenCVImpl ();

  virtual ~PulseReaderOpenCVImpl () {};

  virtual void process (cv::Mat &mat);

  void setOverlay (bool overlaySet);
  sigc::signal<void, PulseDetected> signalPulseDetected;
  sigc::signal<void, PulseUndetected> signalPulseUndetected;
  sigc::signal<void, FrameData> signalFrameData;

};

} /* pulsereader */
} /* module */
} /* kurento */

#endif /*  __PULSE_READER_OPENCV_IMPL_HPP__ */
