/* Autogenerated with kurento-module-creator */

#include "PulseReaderOpenCVImpl.hpp"
#include <KurentoException.hpp>

namespace kurento
{
namespace module
{
namespace pulsereader
{

PulseReaderOpenCVImpl::PulseReaderOpenCVImpl ()
{
}

/*
 * This function will be called with each new frame. mat variable
 * contains the current frame. You should insert your image processing code
 * here. Any changes in mat, will be sent through the Media Pipeline.
 */
void PulseReaderOpenCVImpl::process (cv::Mat &mat)
{
  // FIXME: Implement this
  throw KurentoException (NOT_IMPLEMENTED, "PulseReaderOpenCVImpl::process: Not implemented");
}



void PulseReaderOpenCVImpl::setOverlay (bool overlaySet)
{
  // FIXME: Implement this
  throw KurentoException (NOT_IMPLEMENTED, "PulseReaderOpenCVImpl::setOverlay: Not implemented");
}

} /* pulsereader */
} /* module */
} /* kurento */
