/* Autogenerated with kurento-module-creator */

#include "FrameData.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <time.h>
#include <string>

namespace kurento
{
namespace module
{
namespace pulsereader
{

void
FrameData::Serialize (JsonSerializer &s)
{
  Media::Serialize (s);

  s.SerializeNVP (bpm);
  s.SerializeNVP (id);
  s.SerializeNVP (data);
}

} /* pulsereader */
} /* module */
} /* kurento */

namespace kurento
{

void Serialize (std::shared_ptr<kurento::module::pulsereader::FrameData> &event, JsonSerializer &s)
{
  if (!s.IsWriter && !event) {
    event.reset (new kurento::module::pulsereader::FrameData() );
  }

  if (event) {
    event->Serialize (s);
  }
}

} /* kurento */