/* Autogenerated with kurento-module-creator */

#include "PulseDetected.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <time.h>
#include <string>

namespace kurento
{
namespace module
{
namespace pulsereader
{

void
PulseDetected::Serialize (JsonSerializer &s)
{
  Media::Serialize (s);

  s.SerializeNVP (time);
  s.SerializeNVP (data);
}

} /* pulsereader */
} /* module */
} /* kurento */

namespace kurento
{

void Serialize (std::shared_ptr<kurento::module::pulsereader::PulseDetected> &event, JsonSerializer &s)
{
  if (!s.IsWriter && !event) {
    event.reset (new kurento::module::pulsereader::PulseDetected() );
  }

  if (event) {
    event->Serialize (s);
  }
}

} /* kurento */