/* Autogenerated with kurento-module-creator */

#include "PulseReaderImpl.hpp"
#include "PulseDetected.hpp"
#include "PulseUndetected.hpp"
#include "FrameData.hpp"

#include <jsonrpc/JsonSerializer.hpp>

namespace kurento
{
namespace module
{
namespace pulsereader
{

void dummyPulsereader ()
{
  {
    JsonSerializer s (true);
    std::shared_ptr<PulseReader> object;

    s.SerializeNVP (object);
  }
  {
    JsonSerializer s (true);
    std::shared_ptr<PulseDetected> object;

    s.SerializeNVP (object);
  }
  {
    JsonSerializer s (true);
    std::shared_ptr<PulseUndetected> object;

    s.SerializeNVP (object);
  }
  {
    JsonSerializer s (true);
    std::shared_ptr<FrameData> object;

    s.SerializeNVP (object);
  }
}

} /* pulsereader */
} /* module */
} /* kurento */
