/* Autogenerated with kurento-module-creator */

#ifndef __PULSE_READER_IMPL_FACTORY_HPP__
#define __PULSE_READER_IMPL_FACTORY_HPP__

#include "PulseReaderImpl.hpp"
#include "OpenCVFilterImplFactory.hpp"
#include <Factory.hpp>
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{
namespace module
{
namespace pulsereader
{

class PulseReaderImplFactory : public virtual OpenCVFilterImplFactory
{
public:
  PulseReaderImplFactory () {};

  virtual std::string getName () const {
    return "PulseReader";
  };

private:

  virtual MediaObjectImpl *createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf, std::shared_ptr<MediaPipeline> mediaPipeline, int id, bool overlay) const;
};

} /* pulsereader */
} /* module */
} /* kurento */

#endif /*  __PULSE_READER_IMPL_FACTORY_HPP__ */